# Generated by Django 3.2.6 on 2021-08-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='capacity',
            field=models.IntegerField(default=20),
        ),
    ]
