# Generated by Django 3.2.6 on 2021-08-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_registration_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='time_registered',
            field=models.DateTimeField(default=None),
        ),
    ]
