# Generated by Django 3.2.6 on 2021-08-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20210818_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cellphone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
