# Generated by Django 3.2.6 on 2021-10-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_auto_20210819_1042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seminar',
            options={'ordering': ['date_and_time']},
        ),
        migrations.AddField(
            model_name='seminar',
            name='grade',
            field=models.CharField(choices=[('GRADE11', 'Grade 11'), ('GRADE12', 'Grade 12')], default='GRADE12', max_length=10),
            preserve_default=False,
        ),
    ]
